#!/bin/bash

#----------------
# Name          : run_program
# Project       : digitizer
# Description   : Executes the digitizer program suite
# Author        : E Fournier
# Example Usage : bash run_program
#----------------

main() {
  bash "./_src/main.bash" "$@"
}

main "$@"

