#!/bin/bash

#----------------
# Name          : run_build
# Project       : digitizer
# Description   : Runs the build process for digitizer, outputting an optimized bash script file to the build directory
# Author        : E Fournier
# Dependencies  : shc
# Example Usage : bash run_build
#----------------

make_build_dir() {
  mkdir -p `get_output_dir`
}

get_output_dir() {
  local base_dir="."
  local dir_name="build"

  echo "${base_dir}/${dir_name}"
}

get_file_name() {
  local time_now=`date +"%y%m%d_%H%M"`

  echo "digitizer_${time_now}"
}

get_concat_file_location() {
  local output_name="$1"

  echo "`get_output_dir`/${output_name}"
}

delete_comments() {
  local output_name="$1" 

  sed -i '/^\s*#/d' `get_concat_file_location $output_name`
}

delete_sources() {
  local output_name="$1" 

  sed -i '/^\s*source/d' `get_concat_file_location $output_name`
}

add_shebang() {
  local output_name="$1" 

  sed -i '1s;^;#!/bin/bash\n\n;' `get_concat_file_location $output_name`
}

concatenate_files() {
  local output_name="$1"

  cat \
    "_src/messages/logs.bash" \
    "_src/messages/errors.bash" \
    "_src/messages/help.bash" \
    "_src/utils/constants.bash" \
    "_src/utils/devices.bash" \
    "_src/utils/ffmpeg.bash" \
    "_src/utils/fs.bash" \
    "_src/utils/modes.bash" \
    "_src/utils/time.bash" \
    "_src/utils/timestamps.bash" \
    "_src/input/cut_mode_inputs.bash" \
    "_src/input/device_select.bash" \
    "_src/args/batch_args.bash" \
    "_src/args/capture_audio_args.bash" \
    "_src/args/capture_video_args.bash" \
    "_src/args/cut_video_args.bash" \
    "_src/args/help_args.bash" \
    "_src/args/join_args.bash" \
    "_src/args/mode_args.bash" \
    "_src/args/verbose_args.bash" \
    "_src/args/watch_args.bash" \
    "_src/modes/batch_mode.bash" \
    "_src/modes/capture_audio_mode.bash" \
    "_src/modes/capture_video_mode.bash" \
    "_src/modes/cut_video_mode.bash" \
    "_src/modes/join_mode.bash" \
    "_src/modes/watch_mode.bash" \
    "_src/main.bash" \
      >> `get_concat_file_location "$output_name"`
}

delete_empty_lines() {
  local output_name="$1"

  sed -i '/^$/d' `get_concat_file_location $output_name`
}

main() {
  local output_name=`get_file_name`
  
  make_build_dir
  concatenate_files  "$output_name"
  delete_comments    "$output_name"
  delete_sources     "$output_name"
  add_shebang        "$output_name"
  delete_empty_lines "$output_name"

  printf "\nOutputted script file to `get_concat_file_location $output_name`\n"
}

main "$@"

